[colors.bright]
black = "#444B6A"
blue = "#7DA6FF"
cyan = "#0DB9D7"
green = "#B9F27C"
magenta = "#BB9AF7"
red = "#FF7A93"
white = "#ACB0D0"
yellow = "#FF9E64"

[colors.normal]
black = "#363950"
blue = "#7AA2F7"
cyan = "#449DAB"
green = "#9ECE6A"
magenta = "#AD8EE6"
red = "#F7768E"
white = "#787C99"
yellow = "#E0AF68"

[colors.primary]
background = "#1A1B26"
foreground = "#A9B1D6"
