#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width 2
bspc config window_gap 12

bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a Code desktop='^2' follow=on focus=on
bspc rule -a Google-chrome desktop='^3' follow=on focus=on
bspc rule -a Spotify desktop='^4' follow=on focus=on

bspc config border_width 1.5
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config presel_feedback_color "#7AA2F7"
bspc config focused_border_color "#AD8EE6"
bspc config normal_border_color "#363950"
bspc config active_border_color "#787C99"

picom -f &

xcape -e 'Super_L=Alt_L|F1' &

xrandr --output DP-0 --mode 3440x1440 --primary

sxhkd -c /home/tiago/.config/bspwm/sxhkd/sxhkdrc & 

feh --bg-fill /home/tiago/.config/bspwm/images/background.jpg &

polybar -r -c /home/tiago/.config/bspwm/polybar/config.ini &

if pacman -Ss nvidia-settings; then
    nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=30" &
fi

if openrgb --version >/dev/null; then
    # RAM
    openrgb --device 0 --mode direct --color AD8EE6
    # GPU
    openrgb --device 1 --mode direct --color AD8EE6
    # FANS
    openrgb --device 2 --mode static --color AD8EE6 --brightness 70
fi